stock-management:
  zacks:
    holdings-url: https://www.zacks.com/portfolios/tools/ajxExportExel.php
    body:
      export_data_init_tab: 2282242_update_zYjM1ADO0kjN
    headers:
      Content-Type: application/x-www-form-urlencoded
      Content-Length: 48
  tip-ranks:
    stock-data-url: https://www.tipranks.com/api/portfolio/getPortfolioHoldingStockData/
    stock-data-tickers-query-param: tickers
    news-sentiment-url: https://www.tipranks.com/api/stocks/GetTickersNewsSentiments
    news-sentiment-tickers-query-param: tickers
